// ─────────────────────────────────────────────────────────
// DATOS HARDCODEADOS DEL PERFIL
// Edita este archivo para actualizar cualquier información del sitio
// ─────────────────────────────────────────────────────────

import type { FullProfile } from "@/types/profile";

export const profile: FullProfile = {

  // ── Perfil base ──────────────────────────────────────
  id: "isabel-mendez",
  slug: "isabel-mendez",
  name: "Dra. Isabel Méndez",
  title: "Investigador Titular A",
  institution: "Instituto de Neurobiología, UNAM-Juriquilla",
  photoUrl: null,
  bio: "Investigadora del Instituto de Neurobiología de la UNAM Campus Juriquilla. Mi trabajo se centra en comprender los mecanismos moleculares que vinculan el sistema nervioso con el sistema inmune y el metabolismo, con especial énfasis en el papel del sistema glutamatérgico en el hepatocarcinoma, la cronobiología del metabolismo hepático y la neuroinmunoendocrinología de la prolactina.",
  email: "imendez@inb.unam.mx",
  themePrimary: "#0f172a",
  themeSecondary: "#6366f1",
  themeFont: "Montserrat",

  // ── Niveles académicos ───────────────────────────────
  levels: [
    { id: "lv-1", label: "SNI", value: "Nivel II" },
    { id: "lv-2", label: "PRIDE", value: "Nivel C" },
  ],

  // ── Links académicos ─────────────────────────────────
  academicLinks: [
    { id: "al-1", label: "ORCID", url: "https://orcid.org/0000-0000-0000-0000", icon: "orcid" },
    { id: "al-2", label: "Scopus", url: "https://www.scopus.com/authid/detail.uri?authorId=00000000000", icon: "scopus" },
    { id: "al-3", label: "Web of Science", url: "https://www.webofscience.com/wos/author/record/000000", icon: "wos" },
  ],

  // ── Trayectoria profesional (home) ───────────────────
  career: [
    {
      id: "car-1",
      period: "2015 – presente",
      title: "Investigador Titular A",
      institution: "Instituto de Neurobiología, UNAM-Juriquilla",
    },
    {
      id: "car-2",
      period: "2010 – 2015",
      title: "Investigador Asociado C",
      institution: "Instituto de Neurobiología, UNAM-Juriquilla",
    },
    {
      id: "car-3",
      period: "2008 – 2010",
      title: "Investigador Posdoctoral",
      institution: "Instituto Nacional de Ciencias Médicas y Nutrición Salvador Zubirán, CDMX",
    },
    {
      id: "car-4",
      period: "2003 – 2008",
      title: "Doctorado en Ciencias Biomédicas",
      institution: "Universidad Nacional Autónoma de México",
    },
  ],

  // ── Líneas de investigación ──────────────────────────
  researchLines: [
    {
      id: "rl-1",
      title: "Sistema Glutamatérgico y Cáncer Hepático",
      description:
        "Estudio del papel de los receptores de glutamato (ionotrópicos y metabotrópicos) en la proliferación, migración e invasión de células de hepatocarcinoma. Evaluación de antagonistas glutamatérgicos como estrategia terapéutica en modelos in vitro e in vivo.",
      keywords: ["Glutamato", "Hepatocarcinoma", "Receptores NMDA", "Oncología molecular"],
    },
    {
      id: "rl-2",
      title: "Cronobiología y Metabolismo Hepático",
      description:
        "Análisis de cómo los ritmos circadianos regulan las vías metabólicas del hígado. Identificación de genes reloj como moduladores de la respuesta inflamatoria y el daño hepático crónico.",
      keywords: ["Ritmos circadianos", "Metabolismo", "Reloj biológico", "Hígado"],
    },
    {
      id: "rl-3",
      title: "Neuroinmunoendocrinología: Prolactina",
      description:
        "Caracterización de las acciones de la prolactina sobre el sistema inmune innato y adaptativo. Participación de la prolactina en la fisiopatología de enfermedades autoinmunes como el lupus eritematoso sistémico.",
      keywords: ["Prolactina", "Lupus eritematoso", "Inmunomodulación", "Citocinas"],
    },
  ],

  // ── Proyectos financiados ────────────────────────────
  projects: [
    {
      id: "pj-1",
      code: "PAPIIT IN223124",
      title: "Papel del sistema glutamatérgico en la progresión del hepatocarcinoma: evaluación de dianas terapéuticas",
      agency: "DGAPA-UNAM",
      role: "Responsable Técnica",
      period: "2024 – 2026",
      status: "vigente",
    },
    {
      id: "pj-2",
      code: "CONAHCyT CF-2023-I-768",
      title: "Cronobiología del metabolismo hepático: papel de los genes reloj en el daño hepático",
      agency: "CONAHCyT",
      role: "Responsable Técnica",
      period: "2023 – 2026",
      status: "vigente",
    },
    {
      id: "pj-3",
      code: "PAPIIT IN218020",
      title: "Modulación del sistema inmune por la prolactina en el lupus eritematoso sistémico",
      agency: "DGAPA-UNAM",
      role: "Responsable Técnica",
      period: "2020 – 2023",
      status: "concluido",
    },
    {
      id: "pj-4",
      code: "CONACyT CB-2017-284399",
      title: "Receptores de glutamato en el hígado: función metabólica e implicaciones en la enfermedad",
      agency: "CONACyT",
      role: "Responsable Técnica",
      period: "2018 – 2022",
      status: "concluido",
    },
    {
      id: "pj-5",
      code: "PAPIIT IN224315",
      title: "Acciones de la prolactina en la respuesta inmune innata: macrófagos y células NK",
      agency: "DGAPA-UNAM",
      role: "Responsable Técnica",
      period: "2015 – 2018",
      status: "concluido",
    },
  ],

  // ── Premios y distinciones ───────────────────────────
  awards: [
    {
      id: "aw-1",
      title: "Premio al Mejor Trabajo de Investigación Básica",
      organization: "Sociedad Mexicana de Nutrición y Endocrinología (SMNE)",
      year: 2022,
    },
    {
      id: "aw-2",
      title: "Premio al Mejor Trabajo de Investigación Clínica",
      organization: "Sociedad Mexicana de Nutrición y Endocrinología (SMNE)",
      year: 2019,
    },
    {
      id: "aw-3",
      title: "Distinción Universidad Nacional para Jóvenes Académicos — Área Investigación en Ciencias Naturales",
      organization: "UNAM",
      year: 2016,
    },
  ],

  // ── Publicaciones ────────────────────────────────────
  publications: [
    // Artículos destacados (featured: true)
    {
      id: "pub-1",
      type: "article",
      featured: true,
      title: "Glutamate receptor signaling in hepatocellular carcinoma: therapeutic implications",
      date: "2026-01",
      reference: "Méndez I., García-Ruiz A., Torres-Barrera P. (2026). International Journal of Molecular Sciences, 27(2), 541.",
      pdfUrl: null,
      isDownloadable: false,
      externalUrl: "https://doi.org/10.3390/ijms27020541",
    },
    {
      id: "pub-2",
      type: "article",
      featured: true,
      title: "Antioxidant response and circadian clock disruption in chronic liver disease",
      date: "2025-03",
      reference: "Méndez I., Díaz-Muñoz M., Ramos-Martínez E. (2025). Antioxidants, 14(3), 312.",
      pdfUrl: null,
      isDownloadable: false,
      externalUrl: "https://doi.org/10.3390/antiox14030312",
    },
    {
      id: "pub-3",
      type: "article",
      featured: true,
      title: "Prolactin modulates innate immunity in systemic lupus erythematosus: a review",
      date: "2024-08",
      reference: "Méndez I., Sánchez-López A., Chávez-Rueda K. (2024). Frontiers in Immunology, 15, 1389762.",
      pdfUrl: null,
      isDownloadable: false,
      externalUrl: "https://doi.org/10.3389/fimmu.2024.1389762",
    },
    {
      id: "pub-4",
      type: "article",
      featured: true,
      title: "NMDA receptor antagonism reduces hepatoma cell proliferation via apoptotic pathways",
      date: "2023-11",
      reference: "García-Ruiz A., Méndez I., Flores-Contreras M.A. (2023). Cell Death & Disease, 14, 798.",
      pdfUrl: null,
      isDownloadable: false,
      externalUrl: "https://doi.org/10.1038/s41419-023-06293-0",
    },
    {
      id: "pub-5",
      type: "article",
      featured: true,
      title: "Clock genes BMAL1 and CLOCK regulate lipid metabolism in hepatocyte cell lines",
      date: "2023-04",
      reference: "Méndez I., Díaz-Muñoz M., Pérez-Soto E. (2023). Journal of Hepatology Reports, 5(4), 100691.",
      pdfUrl: null,
      isDownloadable: false,
      externalUrl: "https://doi.org/10.1016/j.jhepr.2023.100691",
    },
    // Artículos completos (featured: false)
    {
      id: "pub-6",
      type: "article",
      featured: false,
      title: "Hyperprolactinemia and autoimmunity: mechanisms and clinical implications",
      date: "2022-06",
      reference: "Méndez I., Vargas-Camacho S. (2022). Autoimmunity Reviews, 21(6), 103086.",
      pdfUrl: null,
      isDownloadable: false,
      externalUrl: "https://doi.org/10.1016/j.autrev.2022.103086",
    },
    {
      id: "pub-7",
      type: "article",
      featured: false,
      title: "Metabotropic glutamate receptors in liver physiology and pathology",
      date: "2022-01",
      reference: "Méndez I., Torres-Barrera P. (2022). Liver International, 42(1), 12–24.",
      pdfUrl: null,
      isDownloadable: false,
      externalUrl: "https://doi.org/10.1111/liv.15091",
    },
    {
      id: "pub-8",
      type: "article",
      featured: false,
      title: "Circadian disruption and hepatocellular carcinoma risk: epidemiology and mechanisms",
      date: "2021-09",
      reference: "Díaz-Muñoz M., Méndez I., Ramos-Martínez E. (2021). Cancers, 13(17), 4378.",
      pdfUrl: null,
      isDownloadable: false,
      externalUrl: "https://doi.org/10.3390/cancers13174378",
    },
    {
      id: "pub-9",
      type: "article",
      featured: false,
      title: "Prolactin receptor signaling in immune cells",
      date: "2020-05",
      reference: "Méndez I., Chávez-Rueda K., Zenteno E. (2020). Frontiers in Endocrinology, 11, 319.",
      pdfUrl: null,
      isDownloadable: false,
      externalUrl: "https://doi.org/10.3389/fendo.2020.00319",
    },
    {
      id: "pub-10",
      type: "article",
      featured: false,
      title: "NMDA receptors outside the brain: expression and function in peripheral tissues",
      date: "2019-03",
      reference: "Méndez I., García-Ruiz A. (2019). Progress in Neurobiology, 175, 41–65.",
      pdfUrl: null,
      isDownloadable: false,
      externalUrl: "https://doi.org/10.1016/j.pneurobio.2019.01.002",
    },
    // Libros
    {
      id: "pub-11",
      type: "book",
      featured: false,
      title: "Lupus eritematoso sistémico: mecanismos moleculares e inmunopatología",
      date: "2020",
      reference: "Méndez I. (Ed.) (2020). Editorial Académica Española. ISBN: 978-3-659-XXXXX-X.",
      pdfUrl: null,
      isDownloadable: false,
      externalUrl: null,
    },
    // Capítulos
    {
      id: "pub-12",
      type: "chapter",
      featured: false,
      title: "Prolactin and autoimmune diseases",
      date: "2021",
      reference: "Méndez I. (2021). En: Prolactin and Autoimmunity. Springer, Nueva York. Cap. 5, pp. 87–114.",
      pdfUrl: null,
      isDownloadable: false,
      externalUrl: null,
    },
    {
      id: "pub-13",
      type: "chapter",
      featured: false,
      title: "Receptores glutamatérgicos en tejidos periféricos: función e implicaciones clínicas",
      date: "2019",
      reference: "Méndez I., García-Ruiz A. (2019). En: Neurobiología del glutamato. UNAM, México. Cap. 8, pp. 145–172.",
      pdfUrl: null,
      isDownloadable: false,
      externalUrl: null,
    },
    {
      id: "pub-14",
      type: "chapter",
      featured: false,
      title: "Cronobiología hepática: el reloj molecular en salud y enfermedad",
      date: "2018",
      reference: "Díaz-Muñoz M., Méndez I. (2018). En: Relojes biológicos: mecanismos y función. Fondo de Cultura Económica, México. Cap. 12, pp. 213–238.",
      pdfUrl: null,
      isDownloadable: false,
      externalUrl: null,
    },
  ],

  // ── Trabajo editorial ────────────────────────────────
  editorialRoles: [
    {
      id: "ed-1",
      role: "Editora Asociada",
      journal: "International Journal of Molecular Sciences",
      publisher: "MDPI",
      url: "https://www.mdpi.com/journal/ijms",
    },
    {
      id: "ed-2",
      role: "Editora Asociada",
      journal: "Frontiers in Immunology",
      publisher: "Frontiers Media",
      url: "https://www.frontiersin.org/journals/immunology",
    },
    {
      id: "ed-3",
      role: "Revisora de Artículos",
      journal: "Scientific Reports",
      publisher: "Nature Portfolio",
      url: null,
    },
    {
      id: "ed-4",
      role: "Revisora de Artículos",
      journal: "Journal of Hepatology",
      publisher: "Elsevier",
      url: null,
    },
    {
      id: "ed-5",
      role: "Revisora de Artículos",
      journal: "PLOS ONE",
      publisher: "Public Library of Science",
      url: null,
    },
  ],

  // ── Tesis dirigidas ──────────────────────────────────
  theses: [
    // En proceso (2026)
    {
      id: "th-1",
      level: "doctorado",
      status: "en_proceso",
      studentName: "Laura González Herrera",
      thesisTitle: "Papel de mGluR5 en la progresión de hepatocarcinoma: estudio en modelo murino",
      year: null,
      institution: "Posgrado en Ciencias Biomédicas, UNAM",
    },
    {
      id: "th-2",
      level: "maestria",
      status: "en_proceso",
      studentName: "Carlos Peña Solís",
      thesisTitle: "Ritmos circadianos y estrés oxidativo hepático en modelo de obesidad inducida por dieta",
      year: null,
      institution: "Maestría en Ciencias Biomédicas, UNAM",
    },
    {
      id: "th-3",
      level: "licenciatura",
      status: "en_proceso",
      studentName: "Sofía Ramírez Vega",
      thesisTitle: "Expresión de receptores NMDA en líneas celulares de hepatocarcinoma humano",
      year: null,
      institution: "Facultad de Química, UNAM",
    },
    // Concluidas — Posdoctorado
    {
      id: "th-4",
      level: "postdoc",
      status: "concluida",
      studentName: "Dr. Alejandro Vargas Camacho",
      thesisTitle: "Modulación de la respuesta Th17 por prolactina en pacientes con LES",
      year: 2023,
      institution: "Instituto de Neurobiología, UNAM",
    },
    // Concluidas — Doctorado
    {
      id: "th-5",
      level: "doctorado",
      status: "concluida",
      studentName: "Ana Paula Torres Barrera",
      thesisTitle: "Glutamato extrasináptico en el microambiente tumoral del hepatocarcinoma",
      year: 2023,
      institution: "Posgrado en Ciencias Biomédicas, UNAM",
    },
    {
      id: "th-6",
      level: "doctorado",
      status: "concluida",
      studentName: "Rodrigo Flores Contreras",
      thesisTitle: "Regulación circadiana de la gluconeogénesis hepática: papel de BMAL1",
      year: 2022,
      institution: "Posgrado en Ciencias Biomédicas, UNAM",
    },
    {
      id: "th-7",
      level: "doctorado",
      status: "concluida",
      studentName: "Elisa Sánchez López",
      thesisTitle: "Receptores de prolactina en macrófagos de pacientes con lupus eritematoso sistémico",
      year: 2020,
      institution: "Posgrado en Ciencias Biomédicas, UNAM",
    },
    // Concluidas — Maestría
    {
      id: "th-8",
      level: "maestria",
      status: "concluida",
      studentName: "Diego Ramos Martínez",
      thesisTitle: "Efecto del MK-801 sobre la viabilidad celular en hepatocitos de rata",
      year: 2024,
      institution: "Maestría en Ciencias Biomédicas, UNAM",
    },
    {
      id: "th-9",
      level: "maestria",
      status: "concluida",
      studentName: "Claudia Pérez Soto",
      thesisTitle: "Alteraciones en la expresión de genes reloj en hígado graso no alcohólico",
      year: 2022,
      institution: "Maestría en Ciencias Biomédicas, UNAM",
    },
    {
      id: "th-10",
      level: "maestria",
      status: "concluida",
      studentName: "Iván García Ruiz",
      thesisTitle: "Hiperprolactinemia experimental y actividad de células NK en modelo murino",
      year: 2021,
      institution: "Maestría en Ciencias Biomédicas, UNAM",
    },
    // Concluidas — Licenciatura
    {
      id: "th-11",
      level: "licenciatura",
      status: "concluida",
      studentName: "Fernanda López Mora",
      thesisTitle: "Expresión de mGluR1 y mGluR5 en tejido hepático normal y tumoral",
      year: 2024,
      institution: "Facultad de Ciencias, UNAM",
    },
    {
      id: "th-12",
      level: "licenciatura",
      status: "concluida",
      studentName: "Héctor Morales Ríos",
      thesisTitle: "Efecto de la prolactina sobre la producción de IL-17 en células T de pacientes con LES",
      year: 2023,
      institution: "Facultad de Química, UNAM",
    },
    {
      id: "th-13",
      level: "licenciatura",
      status: "concluida",
      studentName: "Valeria Juárez Muñoz",
      thesisTitle: "Ritmos de secreción de cortisol y su relación con el daño hepático en pacientes con EHNA",
      year: 2022,
      institution: "Facultad de Medicina, UNAM",
    },
  ],

  // ── Otras asesorías ──────────────────────────────────
  otherAdvising: [
    {
      id: "oa-1",
      type: "Servicio Social",
      description: "Recepción continua de estudiantes de licenciatura para servicio social en el laboratorio.",
    },
    {
      id: "oa-2",
      type: "Estancias de Verano Delfín",
      description: "Supervisión de estudiantes de otras instituciones nacionales en el Programa Delfín de estancias de investigación.",
    },
    {
      id: "oa-3",
      type: "Estancias Verano de la Ciencia Región Centro",
      description: "Participación como tutora en el programa de estancias de verano para estudiantes de bachillerato y licenciatura.",
    },
    {
      id: "oa-4",
      type: "Prácticas Profesionales",
      description: "Asesoría de estudiantes de licenciatura en prácticas profesionales vinculadas al laboratorio.",
    },
  ],

  // ── Docencia ─────────────────────────────────────────
  courses: [
    {
      id: "co-1",
      name: "Inmunología Básica",
      role: "coordinadora",
      program: "Posgrado en Ciencias Biomédicas y en Ciencias Bioquímicas",
      institution: "UNAM",
      period: "2015 – presente",
    },
    {
      id: "co-2",
      name: "Neuroinmunoendocrinología",
      role: "invitada",
      program: "Posgrado en Ciencias Biomédicas",
      institution: "UNAM",
      period: "2016 – presente",
    },
    {
      id: "co-3",
      name: "Biología del Cáncer",
      role: "invitada",
      program: "Posgrado en Ciencias Biomédicas",
      institution: "UNAM",
      period: "2018 – presente",
    },
    {
      id: "co-4",
      name: "Bioquímica Avanzada",
      role: "invitada",
      program: "Posgrado en Ciencias Bioquímicas",
      institution: "UNAM",
      period: "2017 – 2023",
    },
    {
      id: "co-5",
      name: "Hepatología Molecular",
      role: "colaboradora",
      program: "Especialidad en Gastroenterología",
      institution: "Hospital General de México / UNAM",
      period: "2020 – presente",
    },
  ],

  // ── Comités y cuerpos colegiados ─────────────────────
  committees: [
    {
      id: "cm-1",
      role: "Evaluadora de Proyectos",
      organization: "PAPIIT — DGAPA, UNAM",
      period: "2018 – presente",
    },
    {
      id: "cm-2",
      role: "Evaluadora de Proyectos",
      organization: "CONAHCyT — Ciencia Básica y de Frontera",
      period: "2019 – presente",
    },
    {
      id: "cm-3",
      role: "Evaluadora de Proyectos",
      organization: "FONCyT — Argentina (PICT)",
      period: "2021 – presente",
    },
    {
      id: "cm-4",
      role: "Miembro del Comité de Admisión",
      organization: "Posgrado en Ciencias Biomédicas, UNAM",
      period: "2016 – presente",
    },
    {
      id: "cm-5",
      role: "Tutora del Posgrado",
      organization: "Posgrado en Ciencias Biomédicas, UNAM",
      period: "2015 – presente",
    },
    {
      id: "cm-6",
      role: "Tutora del Posgrado",
      organization: "Posgrado en Ciencias Bioquímicas, UNAM",
      period: "2017 – presente",
    },
  ],

  // ── Sociedades científicas ───────────────────────────
  societies: [
    { id: "sc-1", acronym: "AACR", fullName: "American Association for Cancer Research", url: "https://www.aacr.org" },
    { id: "sc-2", acronym: "SMO", fullName: "Sociedad Mexicana de Oncología", url: "https://www.smeo.org.mx" },
    { id: "sc-3", acronym: "EASL", fullName: "European Association for the Study of the Liver", url: "https://easl.eu" },
    { id: "sc-4", acronym: "SMB", fullName: "Sociedad Mexicana de Bioquímica", url: null },
    { id: "sc-5", acronym: "ENDO", fullName: "Endocrine Society", url: "https://www.endocrine.org" },
  ],

  // ── Divulgación y difusión ───────────────────────────
  outreach: [
    // Artículos de divulgación
    {
      id: "out-1",
      type: "article",
      title: "El glutamato más allá del cerebro: un mensajero silencioso en el hígado",
      venue: "Revista Digital Universitaria (RDU)",
      date: "2024-03",
      url: "https://www.revista.unam.mx",
      embedUrl: null,
      mediaType: null,
    },
    {
      id: "out-2",
      type: "article",
      title: "¿Por qué el hígado tiene su propio reloj? Cronobiología y salud hepática",
      venue: "En La Lupa — Ciencia UNAM",
      date: "2023-07",
      url: "https://ciencia.unam.mx",
      embedUrl: null,
      mediaType: null,
    },
    {
      id: "out-3",
      type: "article",
      title: "Lupus, hormonas e inmunidad: el papel oculto de la prolactina",
      venue: "El Universal — Suplemento Ciencia",
      date: "2022-11",
      url: "https://www.eluniversal.com.mx",
      embedUrl: null,
      mediaType: null,
    },
    {
      id: "out-4",
      type: "article",
      title: "Cancer and the brain: the surprising role of neurotransmitters in liver tumors",
      venue: "Boletín UNAM-DGCS",
      date: "2022-04",
      url: "https://www.dgcs.unam.mx",
      embedUrl: null,
      mediaType: null,
    },
    // Apariciones en medios
    {
      id: "out-5",
      type: "media",
      title: "Entrevista: El reloj biológico y la enfermedad hepática",
      venue: "Pulso — Radio UNAM 860 AM",
      date: "2024-01",
      url: null,
      embedUrl: null,
      mediaType: "radio",
    },
    {
      id: "out-6",
      type: "media",
      title: "Entrevista: Lupus, mujeres y ciencia en México",
      venue: "Sinapsis — Radio UNAM",
      date: "2023-05",
      url: null,
      embedUrl: null,
      mediaType: "radio",
    },
    {
      id: "out-7",
      type: "media",
      title: "Mesa Redonda: Avances en investigación básica en cáncer hepático",
      venue: "Centro Cultural Universitario — UNAM",
      date: "2023-02",
      url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      mediaType: "video",
    },
    {
      id: "out-8",
      type: "media",
      title: "Nota periodística: Investigadores de la UNAM descubren nuevo rol del glutamato en el cáncer",
      venue: "Billy Parker Noticias",
      date: "2022-09",
      url: null,
      embedUrl: null,
      mediaType: "prensa",
    },
    // Charlas y ferias de ciencia
    {
      id: "out-9",
      type: "talk",
      title: "¿Cómo funciona tu cerebro? — Semana del Cerebro",
      venue: "Semana del Cerebro, Querétaro",
      date: "2024-03",
      url: null,
      embedUrl: null,
      mediaType: null,
    },
    {
      id: "out-10",
      type: "talk",
      title: "Tu hígado tiene reloj: cronobiología para todos",
      venue: "Feria de Ciencias, Querétaro",
      date: "2023-10",
      url: null,
      embedUrl: null,
      mediaType: null,
    },
    {
      id: "out-11",
      type: "talk",
      title: "Cáncer y neurociencia: una conversación inesperada",
      venue: "Semana del Cerebro, Juriquilla",
      date: "2022-03",
      url: null,
      embedUrl: null,
      mediaType: null,
    },
  ],

  // ── Footer links ─────────────────────────────────────
  footerLinks: [
    { id: "fl-1", label: "Correo", url: "mailto:imendez@inb.unam.mx", icon: "mail" },
    { id: "fl-2", label: "ORCID", url: "https://orcid.org/0000-0000-0000-0000", icon: "orcid" },
    { id: "fl-3", label: "Scopus", url: "https://www.scopus.com", icon: "scopus" },
    { id: "fl-4", label: "Instituto de Neurobiología", url: "https://www.inb.unam.mx", icon: null },
  ],
};
