// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Para migraciones locales, usa DATABASE_URL con la URL directa (sin pooler)
    // En producción (Vercel), usa la URL con pooler (pgbouncer=true)
    url: process.env["DATABASE_URL"],
  },
});
